# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutterNavigate'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'addingFlutterToExistingIosProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for addingFlutterToExistingIosProject
#  For each Podfile target that needs to embed Flutter, you have to add this line
   install_all_flutter_pods(flutter_application_path)


  target 'addingFlutterToExistingIosProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'addingFlutterToExistingIosProjectUITests' do
    # Pods for testing
  end

end
